kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64
clone:
  depth: 1

trigger:
  event:
    include:
      - push
      - pull_request

steps:
  - name: build-check
    image: menny/ndk_ask:1.12.1
    environment:
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      CODECOV_TOKEN: 1a4cd171-2784-4f48-8a62-0b7ec31e6d7e
      GRADLE_USER_HOME: "/drone/src/gradle_home_folder/"
    commands:
      - ./scripts/ci/ci_setup.sh
      - ./scripts/ci/ci_check.sh
      - ./scripts/ci/ci_test_all.sh
      - curl https://codecov.io/bash -o codecov.sh
      - chmod +x codecov.sh
      - ./codecov.sh -X gcov -X coveragepy -X xcode `find . -name "test*UnitTestCoverage.xml" | xargs -n 1 echo -n " -f "`
  - name: deploy-release
    image: menny/ndk_ask:1.12.1
    depends_on:
      - build-check
    environment:
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      BUILD_TYPE: "release"
      REPO_USER: ${DRONE_REPO_OWNER}
      BUILD_COUNT_FOR_VERSION: ${DRONE_BUILD_NUMBER}
      GRADLE_USER_HOME: "/drone/src/gradle_home_folder/"
      KEYSTORE_FILE_URL:
        from_secret: KEYSTORE_FILE_URL
      PUBLISH_CERT_FILE_URL:
        from_secret: PUBLISH_CERT_FILE_URL
      ANYSOFTKEYBOARD_CRASH_REPORT_EMAIL:
        from_secret: ANYSOFTKEYBOARD_CRASH_REPORT_EMAIL
      ANYSOFTKEYBOARD_KEYSTORE_ALIAS:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_ALIAS
      ANYSOFTKEYBOARD_KEYSTORE_KEY_PASSWORD:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_KEY_PASSWORD
      ANYSOFTKEYBOARD_KEYSTORE_PASSWORD:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_PASSWORD
      PUBLISH_APK_SERVICE_ACCOUNT_EMAIL:
        from_secret: PUBLISH_APK_SERVICE_ACCOUNT_EMAIL
    commands:
      - ./scripts/ci/ci_deploy.sh
    when:
      branch:
        - release-branch-v*
      event:
        - push
  - name: dry-run-deploy-release
    image: menny/ndk_ask:1.12.1
    depends_on:
      - build-check
    environment:
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      BUILD_TYPE: "dry-run-release"
      BUILD_COUNT_FOR_VERSION: ${DRONE_BUILD_NUMBER}
      GRADLE_USER_HOME: "/drone/src/gradle_home_folder/"
    commands:
      - wget https://raw.githubusercontent.com/facebook/react-native/63ebbd6bfcc9b76c000ed72a875218d388a7ee09/template/android/app/debug.keystore  -q -O /root/.android/debug.keystore
      - ./gradlew --stacktrace -PwithAutoVersioning assembleRelease generateFdroidYamls
      - cat outputs/fdroid.yaml
    when:
      branch:
        - master
      event:
        - pull_request
  - name: deploy-canary
    image: menny/ndk_ask:1.12.1
    depends_on:
      - build-check
    environment:
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      BUILD_TYPE: "canary"
      REPO_USER: ${DRONE_REPO_OWNER}
      BUILD_COUNT_FOR_VERSION: ${DRONE_BUILD_NUMBER}
      GRADLE_USER_HOME: "/drone/src/gradle_home_folder/"
      KEYSTORE_FILE_URL:
        from_secret: KEYSTORE_FILE_URL
      PUBLISH_CERT_FILE_URL:
        from_secret: PUBLISH_CERT_FILE_URL
      ANYSOFTKEYBOARD_CRASH_REPORT_EMAIL:
        from_secret: ANYSOFTKEYBOARD_CRASH_REPORT_EMAIL
      ANYSOFTKEYBOARD_KEYSTORE_ALIAS:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_ALIAS
      ANYSOFTKEYBOARD_KEYSTORE_KEY_PASSWORD:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_KEY_PASSWORD
      ANYSOFTKEYBOARD_KEYSTORE_PASSWORD:
        from_secret: ANYSOFTKEYBOARD_KEYSTORE_PASSWORD
      PUBLISH_APK_SERVICE_ACCOUNT_EMAIL:
        from_secret: PUBLISH_APK_SERVICE_ACCOUNT_EMAIL
    commands:
      - ./scripts/ci/ci_deploy.sh
    when:
      branch:
        - master
      event:
        - push
