version: 2.0

references:

  container_config: &container_config
    docker:
      - image: menny/ndk_ask:1.12.1

    working_directory: /opt/workspace/

    environment: &base_environment
      TERM: dumb
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    resource_class: medium

  general_cache_key: &general_cache_key
    key: anysoftkeyboard-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle"}}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  check_cache_key: &check_cache_key
    key: anysoftkeyboard-check-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle"}}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  test_cache_key: &test_cache_key
    key: anysoftkeyboard-test-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle"}}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

  cache_paths: &cache_paths
    paths:
      - "~/.gradle"
      - "~/.m2"
      - "/opt/android-sdk-linux/licenses/"

  deploy_template: &deploy_template
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Deploy to Play Store
          command: scripts/ci/ci_deploy.sh ${UPLOAD_KEYSTORE_FILE_URL} ${PUBLISH_CERT_FILE_URL} ${CIRCLE_PROJECT_USERNAME} ${BUILD_TYPE}

      - store_artifacts:
          path: /opt/workspace/app/build/outputs/apk/
          destination: apks/

      - store_artifacts:
          path: /opt/workspace/outputs/
          destination: outputs/

      - store_artifacts:
          path: /opt/workspace/app/build/outputs/mapping/
          destination: mapping/

jobs:

  build_check:
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup environment
          command: scripts/ci/ci_setup.sh

      - run:
          name: Run Checks
          command: scripts/ci/ci_check.sh

      - store_artifacts:
          path: /opt/workspace/app/build/outputs/apk/
          destination: apks/

      - run:
          name: Collect checks reports
          command: |
            rm -rf all-checks-reports || true
            mkdir all-checks-reports || true

            find . -path ./all-checks-reports -prune -o -name "pmd*.html" -exec mkdir -p all-checks-reports/{} \; -exec cp {} all-checks-reports/{}/report.html \;
            find . -path ./all-checks-reports -prune -o -name "checkstyle*.html" -exec mkdir -p all-checks-reports/{} \; -exec cp {} all-checks-reports/{}/report.html \;
            find . -path ./all-checks-reports -prune -o -name "lint-results-*.html" -exec mkdir -p all-checks-reports/{} \; -exec cp {} all-checks-reports/{}/report.html \;

      - store_artifacts:
          path: /opt/workspace/all-checks-reports/
          destination: checks_reports/

      - save_cache:
          <<: *general_cache_key
          <<: *cache_paths

  test:
    parallelism: 3
    <<: *container_config
    environment:
      <<: *base_environment
      CODECOV_TOKEN: 1a4cd171-2784-4f48-8a62-0b7ec31e6d7e

    resource_class: medium

    steps:
      - checkout

      - restore_cache:
          <<: *test_cache_key

      - run:
          name: Run Tests
          command: |
            export TEST_GROUP_INDEX=${CIRCLE_NODE_INDEX}
            export TEST_GROUPS_COUNT=${CIRCLE_NODE_TOTAL}
            echo "Running test group ${TEST_GROUP_INDEX} out of ${TEST_GROUPS_COUNT}..."
            ./scripts/ci/ci_test.sh

      - run:
          name: Collect junit reports
          command: |
            rm -rf all-test-reports || true
            mkdir all-test-reports || true
            find . -path ./all-test-reports -prune -o -name "TEST-*.xml" -exec cp {} all-test-reports/ \;

      - store_test_results:
          path: /opt/workspace/all-test-reports/

      - run:
          name: Push to codecov
          command: |
            curl https://codecov.io/bash -o codecov.sh
            chmod +x codecov.sh
            ./codecov.sh -X gcov -X coveragepy -X xcode `find . -name "test*UnitTestCoverage.xml" | xargs -n 1 echo -n " -f "`

      - save_cache:
          <<: *test_cache_key
          <<: *cache_paths

  heavy_test:
    parallelism: 1
    <<: *container_config
    environment:
      <<: *base_environment
      CODECOV_TOKEN: 1a4cd171-2784-4f48-8a62-0b7ec31e6d7e

    resource_class: medium

    steps:
      - checkout

      - restore_cache:
          <<: *test_cache_key

      - run:
          name: Run Tests
          command: |
            ./scripts/ci/ci_test_heavy.sh

      - run:
          name: Collect junit reports
          command: |
            rm -rf all-test-reports || true
            mkdir all-test-reports || true
            find . -path ./all-test-reports -prune -o -name "TEST-*.xml" -exec cp {} all-test-reports/ \;

      - store_test_results:
          path: /opt/workspace/all-test-reports/

      - run:
          name: Push to codecov
          command: |
            curl https://codecov.io/bash -o codecov.sh
            chmod +x codecov.sh
            ./codecov.sh -X gcov -X coveragepy -X xcode `find . -name "test*UnitTestCoverage.xml" | xargs -n 1 echo -n " -f "`

      - save_cache:
          <<: *test_cache_key
          <<: *cache_paths

  deploy_release:
    <<: *deploy_template
    environment:
      <<: *base_environment
      BUILD_TYPE: "release"

  deploy_canary:
    <<: *deploy_template
    environment:
      <<: *base_environment
      BUILD_TYPE: "canary"

workflows:
  version: 2

  build_check_tests_deploy:
    jobs:
      - build_check
      - test
      - heavy_test:
          requires:
            - build_check
      - deploy_release:
          filters:
            branches:
              only:
                - /release-branch-v.*/
          requires:
            - build_check
            - test
            - heavy_test
      - deploy_canary:
          filters:
            branches:
              only:
                - master
          requires:
            - build_check
            - test
            - heavy_test
