version: 2
jobs:
  build:
    docker:
      - image: menny/android_ndk:1.6.1a

    working_directory: /opt/workspace/

    environment:
      CODECOV_TOKEN: 1a4cd171-2784-4f48-8a62-0b7ec31e6d7e
      COV_REPORT_LOCATION: app/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx1400m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"

    steps:
      - checkout

      - restore_cache:
          key: anysoftkeyboard-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Setup environment
          command: scripts/ci_setup.sh

      - run:
          name: Run Checks
          command: |
            if [ "${CIRCLE_NODE_INDEX}" == "0" ]; then
              ./scripts/ci_check.sh
            fi

      - store_artifacts:
          path: app/build/reports/
          destination: lint_reports/app/

      - store_artifacts:
          path: base/build/reports/
          destination: lint_reports/base/

      - store_artifacts:
          path: jnidictionaryv1/build/reports/
          destination: lint_reports/jnidictionaryv1/

      - store_artifacts:
          path: jnidictionaryv2/build/reports/
          destination: lint_reports/jnidictionaryv2/

      - store_artifacts:
          path: nextword/build/reports/
          destination: lint_reports/nextword/

      - run:
          name: Run Tests
          command: |
            if [ "${CIRCLE_NODE_INDEX}" != "0" ]; then
              export TEST_GROUP_INDEX=$(( ${CIRCLE_NODE_INDEX} - 1 ))
              export TEST_GROUPS_COUNT=$(( ${CIRCLE_NODE_TOTAL} - 1 ))
              echo "Running test group ${TEST_GROUP_INDEX} out of ${TEST_GROUPS_COUNT}..."
              ./scripts/ci_test.sh
              if [[ -f $COV_REPORT_LOCATION ]]; then
                ./scripts/ci_binaries/codecov.sh -X gcov -X coveragepy -f ${COV_REPORT_LOCATION}
              fi
            fi

      - store_artifacts:
          path: app/build/reports/tests/
          destination: tests_reports/

      - store_test_results:
          path: "app/build/test-results/testDebugUnitTest/"

      - deploy:
          name: Deploy to Play Store
          command: |
            echo "Branch ${CIRCLE_BRANCH}"
            echo "Tag ${CIRCLE_TAG}"
            echo "Username ${CIRCLE_PROJECT_USERNAME}"
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "AnySoftKeyboard" ]; then
              ./scripts/ci_deploy.sh $KEYSTORE_FILE_URL $PUBLISH_CERT_FILE_URL
            fi

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/

      - store_artifacts:
          path: app/build/outputs/mapping/
          destination: mapping/

      - save_cache:
          key: anysoftkeyboard-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "circle.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle/wrapper/dists/gradle-3.5-all/"
            - "~/.gradle/caches/modules-2/"
            - "~/.gradle/caches/3.5/"
            - "~/.gradle/caches/build-cache-1/"
            - "./.gradle/buildOutputCleanup"
            - "./.gradle/3.5/"
            - "~/.m2"
