codecov:
  branch: master
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "10...100"

  ignore:
    - "app/src/canary"
    - "app/src/test"
    - "app/src/main/java/com/anysoftkeyboard/ui/dev"
    - "app/src/main/java/android"
    - "app/src/main/java/com/google/android/voiceime"
    - "app/src/main/java/com/emtronics/dragsortrecycler/DragSortRecycler.java"
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 2%
        base: auto

    patch:
      default:
        enabled: yes
        target: auto
          threshold: 10%
          base: auto

comment:
  layout: "header, diff, tree"
  behavior: default
