name: "collect-reports"
author: "menny"
description: "Collect checks report files"

inputs:
  output_folder:
    description: "collect destination"
    default: "collected_reports"
  file_pattern:
    description: "pattern"

runs:
  using: "docker"
  image: "docker://menny/ndk_ask:1.13.1"
  entrypoint: /bin/bash
  args:
    - .github/actions/collect-reports/collect.sh
    - ${{ inputs.output_folder }}
    - ${{ inputs.file_pattern }}

branding:
  icon: 'package'
  color: 'green'
