---
name: "collect-reports"
author: "menny"
description: "Collect checks report files"

inputs:
  output_folder:
    description: "collect destination"
    default: "collected_reports"
    required: true
  file_pattern:
    description: "pattern for files"
    required: true

runs:
  using: "docker"
  image: "docker://ghcr.io/menny/android_ndk:1.19.0"
  entrypoint: /bin/bash
  args:
    - .github/actions/collect-reports/collect.sh
    - ${{ inputs.output_folder }}
    - ${{ inputs.file_pattern }}

branding:
  icon: 'package'
  color: 'green'
