---
name: "collect-reports"
author: "menny"
description: "Collect checks report files"
inputs:
  output_folder:
    description: "collect destination"
    default: "collected_reports"
    required: true
  file_pattern:
    description: "pattern for files"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        .github/actions/collect-reports/collect.sh \
          "${{ inputs.output_folder }}" \
          "${{ inputs.file_pattern }}"
branding:
  icon: 'package'
  color: 'green'
