"""Generate Boshiamy radical tables and CJK character-set raw files.

Design (include-based, build-time, strict)
==========================================
This is a Traditional Chinese IME pack, so every keyboard except the
explicit Boshiamy-Simplified and Boshiamy-Japanese variants must emit
ONLY traditional CJK chars (and ASCII / fullwidth punctuation that
sneak through the radical tables).

Per-keyboard character sets are derived from the Unicode Unihan
``IRG`` (Ideographic Rapporteur Group) source tags, using only the
**core** zones for each script:

* **trad_set** -- ``kIRG_TSource T1-*`` / ``T2-*`` (CNS 11643 planes
  1-2, i.e. Big5 main + extension) ∪ ``kIRG_HSource HB*`` (HK Big5
  planes 0-2) ∪ ``kIRG_HSource HD-*`` (HKSCS supplement).
  Excludes ``T3-``/``T4-``/``T5-``/``T6-``/``T7-``/``TC-``/``TG-``
  (CNS compatibility / extensions / historic) and bare ``H-*`` (HK
  compatibility), which pull in mainland glyphs round-tripped from GB
  (e.g. 头 长 龙 学 国 对 亲) that are *encoded* for TW/HK but not
  standard trad forms.
* **simp_set** -- ``kIRG_GSource G0-*`` (GB 2312 main plane). Excludes
  ``G1-`` (GB 12345 fan-ti zone), ``GE-`` (GB ext shinjitai), ``GH-``
  (HK trad re-encoded), ``GK-`` (Korean kanji in GB ext).
* **jp_set**   -- ``kIRG_JSource`` excluding ``JM*`` (Mojikyo private
  registry, claims essentially every CJK as JP) and ``JK*`` (Korean
  compat additions).

A character is included on a keyboard if and only if every CJK codepoint
in the candidate is a member of that keyboard's set. Kana
(hiragana / katakana) in the value only pass through on the JP keyboard.
Boshiamy entries whose **code** starts with ``,`` (hiragana) or ``.``
(katakana) but whose **value** is a pure script-neutral symbol (e.g.
``，`` ``。`` ``‘``) survive on trad/simp keyboards.

This rule is applied:
* at build time, to the bundled boshiamy radical tables shipped in
  ``res/raw/``;
* at build time, to the Cangjie / Zhuyin / homophone / char-to-zhuyin
  tables generated by ``build_data.py`` (shared trad_set);
* at runtime, to user-supplied overlay tables loaded via SAF (see
  ``RadicalDictionary.loadOverlayRadicals``).

The bundled char-set files (``chinese_chars_trad``,
``chinese_chars_simp``, ``chinese_chars_jp``) are written to ``res/raw/``
so the runtime overlay filter can reuse the exact same data the
build-time filter used. The runtime exclude-filter that used to live in
``RadicalDictionary.getExactMatches`` is removed entirely -- the radical
map is the authoritative answer.

Simplified keyboard ordering
============================
The source table is trad-ordered, so include-filtering it to ``simp_set``
alone keeps the trad order and drops the trad-only primary (e.g. ``iwn``
would surface ``汞`` before ``这``). To match the authentic 台式簡體
(Taiwan-style simplified, a.k.a. ``liu-uni3``) ordering, the simplified
table is instead built by converting each value to its simplified form via
the bundled OpenCC ``chinese_opencc_ts_characters`` map and de-duplicating
per code, so the simplified glyph of the trad primary inherits the primary
slot (``iwn`` -> ``这`` first). See ``build_simp_rows``.

Inputs
======
* ``scripts/openxiami_radicals_raw.tab`` -- radical chart derived from the
  Open Xiami (開放蝦米) community project, a from-scratch re-encoding
  published on Google Sheets under an unconditional grant for any use.
  Generated by ``openxiami_to_raw.py``; see ``NOTICE.md`` for provenance.
* ``scratch/Unihan/Unihan_IRGSources.txt`` -- Unicode Unihan archive
  (download from https://www.unicode.org/Public/UCD/latest/ucd/).
  Falls back to ``$REPO_ROOT/Unihan/Unihan_IRGSources.txt`` and the
  script directory.

Outputs (deterministic, commit alongside this script)
=====================================================
* ``res/raw/chinese_chars_trad``        -- traditional CJK char-set
* ``res/raw/chinese_chars_simp``        -- simplified CJK char-set
* ``res/raw/chinese_chars_jp``          -- Japanese CJK char-set
* ``res/raw/boshiamy_radicals``         -- filtered traditional table
* ``res/raw/boshiamy_radicals_simplified`` -- filtered simplified table
* ``res/raw/boshiamy_radicals_japanese``   -- filtered Japanese table

Run::

    python boshiamy_variants.py
"""

from __future__ import annotations

import os
import sys
from typing import Iterable, List, Set, Tuple

ROOT = os.path.dirname(os.path.abspath(__file__))
RAW_DIR = os.path.join(ROOT, "..", "pack", "src", "main", "res", "raw")

BOSHIAMY_RAW = os.path.join(ROOT, "openxiami_radicals_raw.tab")

# Unihan archive lookup order: scratch (developer convention),
# repo-root sibling, script-sibling. Unihan is gitignored because of its
# size (~50MB unpacked); developers download it locally.
_REPO_ROOT = os.path.abspath(os.path.join(ROOT, "..", "..", "..", ".."))
UNIHAN_CANDIDATES = [
    os.path.join(_REPO_ROOT, "scratch", "Unihan", "Unihan_IRGSources.txt"),
    os.path.join(_REPO_ROOT, "Unihan", "Unihan_IRGSources.txt"),
    os.path.join(ROOT, "Unihan", "Unihan_IRGSources.txt"),
]

OUT_TRAD_CHARS = os.path.join(RAW_DIR, "chinese_chars_trad")
OUT_SIMP_CHARS = os.path.join(RAW_DIR, "chinese_chars_simp")
OUT_JP_CHARS = os.path.join(RAW_DIR, "chinese_chars_jp")

OUT_TRAD = os.path.join(RAW_DIR, "boshiamy_radicals")
OUT_SIMP = os.path.join(RAW_DIR, "boshiamy_radicals_simplified")
OUT_JP = os.path.join(RAW_DIR, "boshiamy_radicals_japanese")
OUT_CHAR_TO_RADICAL = os.path.join(RAW_DIR, "boshiamy_char_to_radical")

# Unicode block predicates ---------------------------------------------------

CJK_RANGES = (
    (0x3400, 0x4DBF),    # CJK Ext A
    (0x4E00, 0x9FFF),    # CJK Unified
    (0xF900, 0xFAFF),    # CJK Compat Ideographs
    (0x20000, 0x2FFFF),  # CJK Ext B/C/D/E/F
    (0x30000, 0x3134F),  # CJK Ext G/H
)
HIRAGANA = (0x3040, 0x309F)
KATAKANA_RANGES = (
    (0x30A0, 0x30FF),
    (0x31F0, 0x31FF),    # Katakana Phonetic Extensions
)


def _in_range(cp: int, lo: int, hi: int) -> bool:
    return lo <= cp <= hi


def _is_cjk_cp(cp: int) -> bool:
    return any(_in_range(cp, lo, hi) for lo, hi in CJK_RANGES)


def _is_kana_cp(cp: int) -> bool:
    if _in_range(cp, *HIRAGANA):
        return True
    return any(_in_range(cp, lo, hi) for lo, hi in KATAKANA_RANGES)


def _codepoints(value: str) -> List[int]:
    return [ord(c) for c in value]


# Unihan reader --------------------------------------------------------------

def _find_unihan() -> str:
    for path in UNIHAN_CANDIDATES:
        if os.path.isfile(path):
            return path
    msg = (
        "Unihan_IRGSources.txt not found. Searched:\n  "
        + "\n  ".join(UNIHAN_CANDIDATES)
        + "\nDownload from https://www.unicode.org/Public/UCD/latest/ucd/"
        + " and place under scratch/Unihan/."
    )
    raise FileNotFoundError(msg)


def _read_irg_sources(
    path: str,
) -> Tuple[Set[int], Set[int], Set[int], Set[int], Set[int]]:
    """Parse Unihan_IRGSources.txt into wide+core script codepoint sets.

    Returns ``(trad, simp, jp, trad_core, simp_core)`` where ``*_core``
    is the "undisputed-core" zone for each script:

    * ``trad_core`` = ``TSource T1-/T2-`` ∪ ``HSource HB*/HD-`` -- the
      canonical trad register (Big5 + CNS planes 1-2 + HKSCS). These
      zones cover every char encoded for TW/HK day-to-day publishing
      while excluding the IRG compatibility/round-tripped mainland zones
      (T3-, T4-T7, TC-TG, bare ``H-``) that pull in shinjitai / simp
      glyphs (e.g. 头 国 学 龙 对 亲).
    * ``simp_core`` = ``GSource G0-*`` -- GB 2312/GB 18030 main plane
      where common mainland chars live (体 头 学 国 ...).

    Zone whitelist / blacklist rationale for the WIDE sets:

    * **trad** = ``kIRG_HSource`` (all HK/HKSCS) ∪ ``kIRG_TSource`` (TW)
      except the ``T3-`` zone, which is the IRG compatibility-only zone
      whose members are not part of current Big5 / CNS standards.
    * **simp** = ``kIRG_GSource`` **except**:
        * ``G1-*`` -- GB 12345 fan-ti (traditional) zone (e.g. 對 G1-3654,
          親 G1-4757). Encoded in mainland for trad context only.
        * ``GE-*`` -- GB 16500-1995 extension; bundles shinjitai-style
          glyphs round-tripped from JIS (e.g. 対 GE-3674).
        * ``GH-*`` -- HKSCS re-encoded in mainland (HK trad chars).
        * ``GK-*`` -- Korean kanji in GB ext (not mainland).
    * **jp** = ``kIRG_JSource`` **except**:
        * ``JM*`` -- Mojikyo private registry (claims essentially every
          CJK as Japanese, defeating script separation).
        * ``JK*`` -- Korean compatibility additions.

    These exclusions preserve common-use script separation while
    accepting that the IRG zones are encoding registries, not
    everyday-use dictionaries.

    Single-character verifications encoded in the tests:
    * 床 (U+5E8A): T1 + G0 + J0 -> trad ✓ simp ✓ jp ✓; trad_core ✓
    * 牀 (U+7240): HSource + T3 -> trad ✓ (via H); not simp/jp
    * 對 (U+5C0D): T1 + G1 + J0 -> trad ✓; NOT simp; jp ✓ (kyujitai)
    * 对 (U+5BF9): T3 + G0 + JMJ -> simp ✓; NOT trad; NOT jp
    * 親 (U+89AA): T1 + G1 -> trad ✓; NOT simp
    * 亲 (U+4EB2): T3 + G0 -> simp ✓; NOT trad
    * 対 (U+5BFE): T3 + GE + J0 -> jp ✓ only
    """
    # Pre-computed prefix sets for branch predictability and to keep
    # the per-line scan O(1).
    simp_excluded_prefixes = ("G1-", "GE-", "GH-", "GK-")
    jp_excluded_prefixes = ("JM", "JK")
    trad: Set[int] = set()
    simp: Set[int] = set()
    jp: Set[int] = set()
    trad_core: Set[int] = set()
    simp_core: Set[int] = set()
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            if not line or line[0] == "#":
                continue
            parts = line.rstrip("\r\n").split("\t", 2)
            if len(parts) != 3:
                continue
            cp_str, field, value = parts
            if not cp_str.startswith("U+"):
                continue
            try:
                cp = int(cp_str[2:], 16)
            except ValueError:
                continue
            if field == "kIRG_HSource":
                trad.add(cp)
                # Core trad zones:
                #   HB0/HB1/HB2 -- HK Big5 (planes 0/1/2), the canonical
                #     TW/HK trad register
                #   HD-         -- HKSCS supplements (legitimate HK trad)
                # Excluded: bare "H-*" zones, which are IRG compatibility
                # blocks containing many GB-round-tripped mainland glyphs
                # (e.g. 头 H-8960, 国 H-98C7, 学 H-8961, 龙 H-89C8).
                if value.startswith("HB") or value.startswith("HD-"):
                    trad_core.add(cp)
            elif field == "kIRG_TSource":
                if not value.startswith("T3-"):
                    trad.add(cp)
                # Core trad zones: T1- (CNS 11643 plane 1) and T2-
                # (CNS 11643 plane 2). Together these form the Big5
                # superset used in modern Taiwan publishing. T3- is
                # compatibility (excluded above); T4-T7/TC-TG cover
                # extension planes that are dominated by historic /
                # simplified / variant glyphs.
                if value.startswith("T1-") or value.startswith("T2-"):
                    trad_core.add(cp)
            elif field == "kIRG_GSource":
                if not value.startswith(simp_excluded_prefixes):
                    simp.add(cp)
                if value.startswith("G0-"):
                    simp_core.add(cp)
            elif field == "kIRG_JSource":
                if not value.startswith(jp_excluded_prefixes):
                    jp.add(cp)
    return trad, simp, jp, trad_core, simp_core


# Boshiamy raw table reader --------------------------------------------------

def _read_raw_table(path: str) -> List[Tuple[str, str]]:
    """Stream ``code\\tvalue`` rows preserving file order.

    Blank lines and lines without a tab are skipped silently. The
    file is read with ``utf-8-sig`` so a stray BOM is tolerated.
    """
    rows: List[Tuple[str, str]] = []
    with open(path, "r", encoding="utf-8-sig") as fh:
        for line in fh:
            stripped = line.rstrip("\r\n")
            if not stripped or "\t" not in stripped:
                continue
            code, _, value = stripped.partition("\t")
            if not code or not value:
                continue
            rows.append((code, value))
    return rows


# Include predicates ---------------------------------------------------------

def _kana_only_code(code: str) -> bool:
    """Boshiamy convention: codes starting with ``,`` or ``.`` are kana.

    These rows live ONLY on the JP keyboard regardless of the value
    **when the value itself contains kana**. Pure-symbol rows whose code
    starts with ``,``/``.`` (e.g. ``,	，``, ``.	。``) are script-neutral
    and are exempted by ``include_for_trad`` / ``include_for_simp``;
    ``_passes_script`` makes the final call from the value.
    """
    return bool(code) and code[0] in (",", ".")


def _passes_script(value: str, cjk_set: Set[int], allow_kana: bool) -> bool:
    """Return True iff every codepoint in ``value`` is acceptable.

    * CJK codepoints must be in ``cjk_set``.
    * Kana codepoints (hiragana / katakana) pass iff ``allow_kana``.
    * All other codepoints (ASCII, punctuation, emoji, kaomoji symbols)
      always pass -- they're script-neutral.
    """
    for cp in _codepoints(value):
        if _is_cjk_cp(cp):
            if cp not in cjk_set:
                return False
        elif _is_kana_cp(cp):
            if not allow_kana:
                return False
        # else: script-neutral; always passes.
    return True


def include_for_trad(code: str, value: str, trad_set: Set[int]) -> bool:
    # Codes starting with ``,``/``.`` are the JP-input convention, but the
    # raw table also contains pure-symbol values under those codes
    # (``,	，``, ``.	。``, ``,'	‘``, etc.) that are useful on every
    # keyboard. Defer the decision to _passes_script: kana values fail
    # (allow_kana=False); script-neutral symbols pass.
    return _passes_script(value, trad_set, allow_kana=False)


def include_for_simp(code: str, value: str, simp_set: Set[int]) -> bool:
    # See include_for_trad for the rationale around comma/period codes.
    return _passes_script(value, simp_set, allow_kana=False)


# Trad -> simp reordering for the simplified keyboard -------------------------
#
# The source table is trad-ordered (its first row per code is the trad
# primary, e.g. iwn -> 這). Merely include-filtering it to simp_set keeps that
# trad order and drops the trad-only primary, so the simplified keyboard would
# surface a secondary char first (iwn -> 汞) instead of the simplified form of
# the primary (iwn -> 这). To match the authentic 台式簡體 (Taiwan-style
# simplified, a.k.a. liu-uni3) ordering, we convert each value to its
# simplified form using the bundled OpenCC TSCharacters map and dedup per code,
# so the simplified glyph of the trad primary inherits the primary slot.

TS_CHARS_PATH = os.path.join(RAW_DIR, "chinese_opencc_ts_characters")


def _load_t2s(path: str) -> dict:
    """Load a char-level trad->simp map from an OpenCC TSCharacters file.

    Lines are ``key\\tvalue(s)`` where multiple space-separated values encode
    context-dependent variants; we deterministically take the first (the
    OpenCC-preferred simplified form). ``#`` comments and blank lines are
    skipped.
    """
    mapping: dict = {}
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\r\n")
            if not line or line[0] == "#" or "\t" not in line:
                continue
            key, _, value = line.partition("\t")
            first = value.split(" ", 1)[0].strip()
            if key and first:
                mapping[key] = first
    return mapping


def _to_simplified(value: str, t2s: dict) -> str:
    return "".join(t2s.get(ch, ch) for ch in value)


def build_simp_rows(
    raw_rows: List[Tuple[str, str]], simp_set: Set[int], t2s: dict
) -> List[Tuple[str, str]]:
    """Build the simplified table rows in authentic 台式簡體 order.

    For each trad-ordered raw row, prefer its simplified conversion when that
    conversion is a valid simp char (so 這 -> 这 takes the primary slot);
    otherwise fall back to the original value when it is already valid simp
    (so no code that has candidates today ends up empty). Duplicates within a
    code are dropped keeping first occurrence, preserving the source priority.
    """
    out: List[Tuple[str, str]] = []
    seen_per_code: dict = {}
    for code, value in raw_rows:
        simplified = _to_simplified(value, t2s)
        if include_for_simp(code, simplified, simp_set):
            chosen = simplified
        elif include_for_simp(code, value, simp_set):
            chosen = value
        else:
            continue
        seen = seen_per_code.setdefault(code, set())
        if chosen in seen:
            continue
        seen.add(chosen)
        out.append((code, chosen))
    return out


def include_for_jp(code: str, value: str, jp_set: Set[int]) -> bool:
    # JP keyboard accepts kana (with or without the kana code prefix) and
    # CJK kanji that are in jp_set.
    return _passes_script(value, jp_set, allow_kana=True)


# Writers --------------------------------------------------------------------

def _atomic_write(path: str, lines: Iterable[str]) -> None:
    tmp = path + ".tmp"
    try:
        with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
            for line in lines:
                fh.write(line)
                fh.write("\n")
        os.replace(tmp, path)
    except OSError as e:
        try:
            if os.path.exists(tmp):
                os.remove(tmp)
        except OSError:
            pass
        print(
            f"error: failed to write {path}: {e}. "
            "If on Windows, close Android Studio and stop the Gradle daemon "
            "(./gradlew --stop) and re-run.",
            file=sys.stderr,
        )
        raise


def _write_charset(path: str, cps: Set[int]) -> int:
    # Sorted by codepoint for deterministic output and easy human diffs.
    sorted_cps = sorted(cps)
    _atomic_write(path, (chr(cp) for cp in sorted_cps))
    return len(sorted_cps)


def _write_table(path: str, rows: List[Tuple[str, str]]) -> None:
    _atomic_write(path, (f"{c}\t{v}" for c, v in rows))


def build_char_to_radical(
    rows: List[Tuple[str, str]]
) -> List[Tuple[str, str]]:
    """Build the reverse ``value -> code`` lookup used by homophone search.

    Derived from the same rows we ship, so it can never drift from the
    forward table. When a value has several codes we keep the shortest
    (then alphabetically first) one, which is the code a user is most
    likely to be taught.
    """
    best: dict = {}
    for code, value in rows:
        current = best.get(value)
        if current is None or (len(code), code) < (len(current), current):
            best[value] = code
    return [(v, best[v]) for v in sorted(best)]


# Main -----------------------------------------------------------------------

def main(argv: List[str]) -> int:
    unihan_path = _find_unihan()
    print(f"reading {unihan_path}")
    trad_cps, simp_cps, jp_cps, trad_core, simp_core = _read_irg_sources(
        unihan_path
    )

    # Trad keyboards (Boshiamy / Cangjie / Zhuyin) use the strict
    # core-trad set: IRG TSource T1-/T2- ∪ HSource HB*/HD-. This excludes
    # the IRG compatibility / round-tripped mainland glyphs (头 国 学
    # 龙 对 亲, etc.) that would otherwise pollute trad candidate lists.
    #
    # Simp and JP keyboards are NOT tightened -- this is a Traditional
    # Chinese IME pack and the simp + JP variants are explicitly opt-in
    # alternate keyboards that should keep their full natural register.
    trad_cps = trad_core

    # The on-disk jp char-set is the single source of truth for the
    # Android runtime overlay filter, so kana codepoints (which always
    # pass _passes_script with allow_kana=True) are folded into the
    # file as well. Trad/simp files stay CJK-only so the Java filter
    # naturally rejects rows whose value contains kana.
    jp_charset_for_file: Set[int] = set(jp_cps)
    for lo, hi in (HIRAGANA, *KATAKANA_RANGES):
        jp_charset_for_file.update(range(lo, hi + 1))

    n_trad = _write_charset(OUT_TRAD_CHARS, trad_cps)
    n_simp = _write_charset(OUT_SIMP_CHARS, simp_cps)
    n_jp = _write_charset(OUT_JP_CHARS, jp_charset_for_file)
    print(
        f"wrote char-sets: trad={n_trad} simp={n_simp} jp={n_jp}"
    )

    raw_rows = _read_raw_table(BOSHIAMY_RAW)
    print(f"read {len(raw_rows)} raw boshiamy rows")

    trad_rows = [
        (c, v) for c, v in raw_rows if include_for_trad(c, v, trad_cps)
    ]
    t2s = _load_t2s(TS_CHARS_PATH)
    simp_rows = build_simp_rows(raw_rows, simp_cps, t2s)
    jp_rows = [
        (c, v) for c, v in raw_rows if include_for_jp(c, v, jp_cps)
    ]

    _write_table(OUT_TRAD, trad_rows)
    _write_table(OUT_SIMP, simp_rows)
    _write_table(OUT_JP, jp_rows)
    # Reverse lookup is derived from the trad table we just wrote, so the
    # two can never disagree.
    c2r = build_char_to_radical(trad_rows)
    _write_table(OUT_CHAR_TO_RADICAL, c2r)
    print(
        f"wrote boshiamy tables: trad={len(trad_rows)} "
        f"simp={len(simp_rows)} jp={len(jp_rows)} "
        f"char_to_radical={len(c2r)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
