name: "deployment-request"
author: "menny"
description: "Performs a deploy request"

inputs:
  ref:
    description: "ref (branch) to publish"
    required: true
  sha:
    description: "commit to deploy"
    required: true
  api_user_name:
    description: "the username to use for API calls"
    required: true
  api_user_token:
    description: "the user API token to use for API calls"
    required: true
  reports_folder:
    description: "Where to store requests and responses files."
    required: true

runs:
  using: "docker"
  image: "docker://menny/ndk_ask:1.13.6"
  entrypoint: /bin/bash
  args:
    - .github/actions/deploy-request/request.sh
    - ${{ inputs.ref }}
    - ${{ inputs.sha }}
    - ${{ inputs.api_user_name }}
    - ${{ inputs.api_user_token }}
    - ${{ inputs.reports_folder }}

branding:
  icon: 'package'
  color: 'purple'
