package com.anysoftkeyboard.api;

public class MediaInsertion {
    public final static String INTENT_MEDIA_INSERTION_REQUEST_ACTION = "com.anysoftkeyboard.api.INTENT_MEDIA_INSERTION_REQUEST_ACTION";
    public final static String INTENT_MEDIA_INSERTION_REQUEST_MEDIA_REQUEST_ID_KEY = "com.anysoftkeyboard.api.INTENT_MEDIA_INSERTION_REQUEST_MEDIA_REQUEST_ID_KEY";
    public final static String INTENT_MEDIA_INSERTION_REQUEST_MEDIA_MIMES_KEY = "com.anysoftkeyboard.api.INTENT_MEDIA_INSERTION_REQUEST_MEDIA_MIMES_KEY";

    public final static String BROADCAST_INTENT_MEDIA_INSERTION_AVAILABLE_ACTION = "com.anysoftkeyboard.api.BROADCAST_INTENT_MEDIA_INSERTION_AVAILABLE_ACTION";
    public final static String BROADCAST_INTENT_MEDIA_INSERTION_MEDIA_URI_KEY = "com.anysoftkeyboard.api.BROADCAST_INTENT_MEDIA_INSERTION_MEDIA_URI_KEY";
    public final static String BROADCAST_INTENT_MEDIA_INSERTION_REQUEST_ID_KEY = "com.anysoftkeyboard.api.BROADCAST_INTENT_MEDIA_INSERTION_REQUEST_ID_KEY";
    public final static String BROADCAST_INTENT_MEDIA_INSERTION_MEDIA_MIMES_KEY = "com.anysoftkeyboard.api.BROADCAST_INTENT_MEDIA_INSERTION_MEDIA_MIMES_KEY";
}
