name: "Code Cov"
author: "menny"

runs:
  using: "docker"
  image: "docker://menny/ndk_ask:1.13.1"
  env:
    TERM: dumb
    CODECOV_TOKEN: 1a4cd171-2784-4f48-8a62-0b7ec31e6d7e
  entrypoint: /bin/bash
  args:
    - .github/actions/codecov/upload_coverage.sh

branding:
  icon: 'pie-chart'
  color: 'green'
