codecov:
  branch: master
  require_ci_to_pass: no
  notify:
    wait_for_ci: no

coverage:
  precision: 2
  round: down
  range: "65...100"

  ignore:
    - "app/src/canary"
    - "app/src/test"
    - "app/src/main/java/com/anysoftkeyboard/ui/dev"
    - "app/src/main/java/android"
    - "app/src/main/java/com/google/android/voiceime"
    - "app/src/main/java/com/emtronics/dragsortrecycler/DragSortRecycler.java"
  status:
    project: off
    patch: off

comment:
  layout: "header, diff, tree"
  behavior: default
