name: close-stales

on:
  schedule:
    - cron: '27 10 * * *'

jobs:
  stale-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 400 days with no activity. Remove stale label or comment or this will be closed in 8 days'
          days-before-stale: 400
          days-before-close: 8
          operations-per-run: 5
  stale-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This pull-request is stale because it has been open 40 days with no activity. Remove stale label or comment or this will be closed in 8 days'
          days-before-stale: 40
          days-before-close: 8
          operations-per-run: 5
