name: localization-review
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/res/values/strings.xml'

jobs:
  localization-review:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6.0.2
      - name: AI Translation Review
        uses: menny/cassandra@v0.3.0
        with:
          reviewer_github_token: ${{ secrets.AI_CODE_REVIEW_GH_TOKEN }}
          provider_api_key: ${{ secrets.GEMINI_2_5_FLASH_API_KEY }}
          main_guidelines: '.cassandra/translation_rules.md'
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
